FROM alpine:latest as downloader

ARG PB_VERSION=0.19.4

RUN apk add --no-cache \
  unzip \
  ca-certificates

ADD https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip /tmp/pb.zip
RUN unzip /tmp/pb.zip -d /pb/

FROM alpine:latest

RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*

EXPOSE 8080

COPY --from=downloader /pb/pocketbase /pb/pocketbase
CMD ["/pb/pocketbase", "serve", "--http=0.0.0.0:8080"]
