name: Build, push & deploy

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - app: skiftesgatan
            dockerfile: ./Dockerfile
            image: ghcr.io/ollema/skiftesgatan
            token_name: APP_TOKEN_SKIFTESGATAN
          - app: pocketbase
            dockerfile: ./Dockerfile.pocketbase
            image: ghcr.io/ollema/skiftesgatan-pocketbase
            token_name: APP_TOKEN_POCKETBASE

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "PUBLIC_DSN=${{ secrets.PUBLIC_DSN }}"

      - name: Deploy
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: https://server.ollema.xyz
          app: ${{ matrix.app }}
          token: ${{ secrets[matrix.token_name] }}
          image: ${{ steps.meta.outputs.tags }}
